import {
  getProductById,
  getProductIds,
  getProductReviews,
  getProductStock,
} from 'api/product';
import ImageSlider from 'components/imageSlider';
import Review from 'components/review';
import Head from 'next/head';
import Image from 'next/image';
import { FC } from 'react';
import { IRecord, IRecordReview, IReview, TParam } from 'types/product';
import { handleStockAvailable } from 'utils/helper';
import styles from '../styles/Home.module.css';

interface ProductPageProps {
  record: IRecord;
  reviews: IRecordReview[];
  stock: number;
}

const ProductPage: FC<ProductPageProps> = ({ record, reviews, stock }) => {
  const product = record.fields;
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Product Detail </h1>
        <div className="my-8">
          <div className={'grid md:grid-cols-2 gap-4 p-8'}>
            <div className="flex flex-col space-y-4 justify-center">
              <h1 className="font-bold text-2xl">{product.Name}</h1>
              <h2>Brand: {product.Brand}</h2>
              <div className="px-4 py-1 bg-yellow-400 w-fit rounded-lg text-white">
                {product.Price} $
              </div>
              <div className="text-red-600 italic">
                {handleStockAvailable(stock)}
              </div>
              <p>{product.Description}</p>
            </div>
            <div>
              <ImageSlider pictures={product.pictures} />
            </div>
          </div>
        </div>
        <div className="w-4/5 mx-auto">
          <h2 className="font-semibold text-2xl text-center">
            Reviews
          </h2>
          <div className="grid grid-cols-2">
            {reviews.map((review) => (
              <Review key={review.id} review={review.fields} />
            ))}
          </div>
        </div>
      </main>

      <footer className={styles.footer}>Copyright © 2022 7hu</footer>
    </div>
  );
};

export const getStaticPaths = async () => {
  const paths = await getProductIds();
  return { paths, fallback: false };
};

export const getStaticProps = async (params: TParam) => {
  const record = await getProductById(params.params.id);
  const recordReviews = await getProductReviews(record.fields.Id);
  const recordStock = await getProductStock(record.fields.Id);
  return {
    props: {
      record,
      reviews: recordReviews.records,
      stock: recordStock.records[0].fields.Stock,
    },
  };
};

export default ProductPage;
