import Head from 'next/head';
import styles from '../styles/Home.module.css';

export default function ProductPage() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>List of products </h1>

        <div className={styles.grid}></div>
      </main>

      <footer className={styles.footer}>Copyright © 2022 7hu</footer>
    </div>
  );
}
