import { getProducts } from 'api/product';
import Product from 'components/product';
import Head from 'next/head';
import { FC } from 'react';
import { IRecord } from 'types/product';

interface HomeProps {
  records: IRecord[];
}

const Home: FC<HomeProps> = ({ records }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="py-8 mx-auto container">
        <h1 className="text-5xl font-bold text-center mb-8">
          List of products
        </h1>
        <div className="grid grid-cols-3 gap-4">
          {records.length > 0 ? (
            records.map((record: IRecord) => (
              <Product
                key={record.id}
                recordId={record.id}
                product={record.fields}
              />
            ))
          ) : (
            <div>No Data</div>
          )}
        </div>
      </main>

      <footer className="text-center border-t py-4 ">
        Copyright © 2022 7hu
      </footer>
    </div>
  );
};

export const getStaticProps = async () => {
  const { records } = await getProducts();
  return { props: { records: records ?? [] } };
};

export default Home;
