import { getProducts } from 'api/product';
import Product from 'components/product';
import Head from 'next/head';
import { FC } from 'react';
import { IRecord, IRecords } from 'types/product';
import styles from '../styles/Home.module.css';

interface HomeProps {
  records: IRecord[];
}

const Home: FC<HomeProps> = ({ records }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>List of products </h1>

        <div className={styles.grid}>
          {records.length > 0 ? (
            records.map((record: IRecord) => (
              <Product key={record.id} product={record.fields} />
            ))
          ) : (
            <div>No Data</div>
          )}
        </div>
      </main>

      <footer className={styles.footer}>Copyright © 2022 7hu</footer>
    </div>
  );
};

export const getStaticProps = async () => {
  const { records } = await getProducts();
  return { props: { records: records ?? [] } };
};

export default Home;
